AWSTemplateFormatVersion: '2010-09-09'
Description: Criar EC2 com Nginx, script de inicialização e tags

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-020cba7c55df1f615
      KeyName: Server-nginx
      SubnetId: "*****"
      SecurityGroupIds:
        - "*****"
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 8
            VolumeType: gp3
            Encrypted: false
            DeleteOnTermination: true
            Iops: 3000
            SnapshotId:  "*****"
            Throughput: 125
      Tags:
        "*****"
      UserData:
        Fn::Base64: |
          #!/bin/bash

          # Atualiza pacotes
          apt update -y && apt upgrade -y

          # Instala nginx, git, node e npm
          apt install -y nginx git curl
          curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
          apt install -y nodejs

          # Clona repositório
          cd /opt
          git clone https://github.com/Portifolio.git
          cd Portifolio

          # Instala dependências e build
          npm install
          npm run build

          # Copia build para o diretório do nginx
          rm -rf /var/www/html/*
          cp -r build/* /var/www/html/

          # Inicia o NGINX
          systemctl start nginx
          systemctl enable nginx

          # Cria script de monitoramento
          cat << 'EOF' > /usr/local/bin/monitor.sh
          #!/bin/bash
          URL=$(curl -s https://checkip.amazonaws.com)
          LOG="/var/log/monitor.log"
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://$URL)
          DATA=$(date "+%Y-%m-%d %H:%M:%S")
          if [ "$STATUS" -ne 200 ]; then
            echo "$DATA - ERRO: Aplicação fora do ar (status $STATUS)" >> $LOG
            curl -H "Content-Type: application/json" \
                 -X POST \
                 -d "{\"content\": \"🚨 ALERTA: Site fora do ar! Código $STATUS\"}" \
                 https://discord.com
          fi
          EOF
          chmod +x /usr/local/bin/monitor.sh
          touch /var/log/monitor.log
          (crontab -l 2>/dev/null; echo "* * * * * /usr/local/bin/monitor.sh") | crontab -
          systemctl restart nginx

      MetadataOptions:
        HttpEndpoint: enabled
        HttpTokens: required
        HttpPutResponseHopLimit: 2

